/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_poire_buzz4j_HarfBuzz */

#ifndef _Included_dev_poire_buzz4j_HarfBuzz
#define _Included_dev_poire_buzz4j_HarfBuzz
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jintArray JNICALL Java_dev_poire_buzz4j_HarfBuzz_shapeStringGlyphs
  (JNIEnv *env, jclass clazz, jstring fontPath, jstring text);

#ifdef __cplusplus
}
#endif
#endif
