/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_poire_buzz4j_HarfBuzz */

#ifndef _Included_dev_poire_buzz4j_HarfBuzz
#define _Included_dev_poire_buzz4j_HarfBuzz
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_poire_buzz4j_HarfBuzz
 * Method:    shapeBuffer
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_dev_poire_buzz4j_HarfBuzz_shapeBuffer
  (JNIEnv *env, jclass clazz, jstring fontPath, jbyteArray buffer);

#ifdef __cplusplus
}
#endif
#endif
